name: CI/CD workflow for Sonar Code scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Ici tu pourras plus tard ajouter :
      # - install PHP deps (composer)
      # - npm install / build front
      # - tests, etc.

      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v6
        with:
          projectBaseDir: .
          args: >
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.organization=NILOTRUG
            -Dsonar.projectKey=B1-UE2-2-D-veloppement-web-full-stack
            -Dsonar.sources=.
            -Dsonar.exclusions=**/vendor/**,**/node_modules/**
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

